services:
  app:
    image: ghcr.io/my-it-crew/ucpe-webapp:latest
    ports:
      - "3000:3000"
    env_file: .env
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
